fc:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 106.54.6.144
    port: 3306
    database: fuchuang_a15
    username: root
    password: xiandan*19780815

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJKucGDTSptHqUMaNm6
    access-key-secret: SImboVg8yt9x1oEZRZZGkgxkkD9QjO
    bucket-name: insistentwind
  redis:
    host: localhost
    port: 6379
    database: 10
  rabbitmq:
    host: 106.54.6.144
    port: 5672
    username: user
    password: user123456
    virtual-host: /