server:
  port: 8082
spring:
  profiles:
    active: dev
  datasource:
    druid:
      db01:
        driver-class-name: ${fc.datasource.driver-class-name}
        url: jdbc:mysql://${fc.datasource.host}:${fc.datasource.port}/${fc.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: ${fc.datasource.username}
        password: ${fc.datasource.password}
        type: com.alibaba.druid.pool.DruidDataSource
      db02:
        driver-class-name: ${fc.datasource.driver-class-name}
        url: jdbc:mysql://119.91.138.143:${fc.datasource.port}/${fc.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
        username: ${fc.datasource.username}
        password: ${fc.datasource.password}
        type: com.alibaba.druid.pool.DruidDataSource



#    password: ${fc.redis.password}
  #文件上传的配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  rabbitmq:
    host: ${fc.rabbitmq.host}
    port: 5672
    username: user
    password: user123456
    virtual-host: /

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ning.domain.entity
#  configuration:
#    # 日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      ##逻辑删除字段
      logic-delete-field: delFlag
      #删除为1
      logic-delete-value: 1
      #未删除为0
      logic-not-delete-value: 0
      #设置数据库字段自动id
      id-type: auto

